# Generated by Django 5.0.6 on 2024-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_cook_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.CharField(choices=[('Bakery', 'Выпечка'), ('Breakfast', 'Завтрак'), ('Dessert', 'Десерт'), ('On coals', 'На углях'), ('Beverages', 'Напитки'), ('Soups', 'Супы'), ('Cold snacks', 'Холодные закуски'), ('Hot dishes', 'Горячие блюда'), ('Side dishes', 'Гарниры')], default=None, max_length=40),
            preserve_default=False,
        ),
    ]
