# Generated by Django 5.0.6 on 2024-07-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_dish_dish_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='dishes',
        ),
    ]
